# App config
app:
  name: kirin-consumer

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 51MB
  session:
    timeout: 3d
  application:
    name: kirin-dubbo-service-consumer

server:
  servlet:
    context-path: /api
  port: 8081


# Dubbo config
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: org.kirin.consumer

kirin:
  service:
    version: 1.0.0
    url: nacos://127.0.0.1:8848

logging:
  file: log4j2.xml