spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pay_user
    password: welcome
    url: jdbc:mysql://127.0.0.1:3306/pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 51MB
  session:
    timeout: 3d

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

server:
  servlet:
    context-path: /api

logging:
  file: log4j2.yaml