--liquibase formatted sql

--changeset kirin:1
CREATE TABLE v_account (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
  account_no VARCHAR(128) NOT NULL COMMENT '账户号',
  account_type VARCHAR(16) NOT NULL COMMENT '账户类型',
  amount DECIMAL NOT NULL DEFAULT 0.00 COMMENT '账户余额, 默认为 0.00',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE INDEX INDEX_USER_ID ON v_account(user_id);
CREATE INDEX INDEX_ACCOUNT_NO ON v_account(account_no);
