# App config
app:
  name: kirin

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pay_user
    password: welcome
    url: jdbc:mysql://127.0.0.1:3306/pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 51MB
  session:
    timeout: 3d
  application:
    name: kirin-dubbo-service-provider

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

server:
  servlet:
    context-path: /api
  port: 8080


# Dubbo config
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo:
  scan:
    base-packages: org.kirin
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A

kirin:
  service:
    version: 1.0.0
  group: hisoka

logging:
  file: log4j2.yaml